services:

  mysql-db:
    image: mysql:latest
    container_name: mysql-container
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ibm1

    ports:
      - "2003:3306"

    networks:
      - springboot-mysql-network

  app:
    image: springboot-docker:0.1.release
    container_name: springboot-app

    depends_on:
      - mysql-db

    ports:
      - "9090:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/ibm1
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

    networks:
      - springboot-mysql-network

networks:
  springboot-mysql-network:
    driver: bridge